### ISSUE TITLE
unable to encode getUserDevice

### ISSUE THREAD

**Issue by kubi-ozisik** [toshvelaga/livestream#2]
I tried to use the ffmpeg command you have here. It works fine when I am getting the stream from getUserMedia. However, if I changed the stream from webcam to screencast, it doesn't work. Is there any solution to this?

**Comment by toshvelaga** [comment]
I don't think it should be an ffmpeg issue, one thing you can try is set the default to getDisplayMedia instead of getUserMedia on the frontend and try streaming to youtube. You should be able to see your screen streamed. I tested this quite a bit in the past and it seemed to work.

**Comment by kubi-ozisik** [comment]
I tried it as well. I created a standalone simple react app. Every other options are same but the getDisplayMedia.. is there any limitations on size of the chunks maybe?

**Comment by toshvelaga** [comment]
Apologies for the late reply, that's a good question, tbh i don't think the chunk size is an issue. If you want I am happy to hop on a call to take a look at your code.

**Comment by kubi-ozisik** [comment]
Thank you for returning to me back. I've pushed the repo here. Would you mind checking it first? It's basically the same though. I'm creating the Broadcast and Stream via Postman and using the `youtubeDestinationUrl` in server.ts file at line #40.

https://github.com/kubi-ozisik/youtube-streamer

we could make a call as well and that would be really appreciated!

**Comment by kubi-ozisik** [comment]
also, created an issue here: https://github.com/kubi-ozisik/youtube-streamer/issues/1

**Comment by toshvelaga** [comment]
ok great will run your code tomorrow (have work to do today). If I can't get it to work I can create a minimum example without all the auth and database stuff which I think would be easier to follow along with.

**Comment by kubi-ozisik** [comment]
that repo I created is exactly how it is structured. (w/out the auth and db stuff) The rest is basically the part I took from this repo.

**Comment by toshvelaga** [comment]
I've forked your code and made some changes to get it easier to run. Instead of youtube I've used Twitch which is less error prone. Also I changed the mediaRecorder to 1000 instead of 100. The code seems to work on my end and I streamed screen sharing to Twitch without issue. Let me know if you have any questions. 

Here's the link: https://github.com/toshvelaga/twitch-streamer

<img width="1176" alt="Screen Shot 2023-01-27 at 6 11 41 PM" src="https://user-images.githubusercontent.com/38474161/215236755-c11fddc3-5e8f-4003-9bad-801ed4b5b808.png">

**Comment by kubi-ozisik** [comment]
hey @toshvelaga , sorry for the late reply. I couldn't find time to test it.

It's so weird that I cloned your repo (with twitch settings) and with no change I tested it. The same thing. It works perfectly with the camera (mediaDevices.getUserMedia) but it doesn't work with getDisplayMedia. At this point, I'm thinking that the ffmpeg installation or maybe my environment is missing some plugins? 

I have cloned the same to my mac environment, and installed ffmpeg with `brew install ffmpeg` but the same result. Is there any way to compare our ffmpeg environmental configuration?

**Comment by kubi-ozisik** [comment]
OK. It works great with Twitch (both getUserMedia and getDisplayMedia) but not with YouTube. (Webcam works fine, just the screencast)
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/80417621/216516502-da3f964e-fd18-40f6-8a86-927a961baf05.png">

**Comment by toshvelaga** [comment]
yeah I haven't had that issue before on Youtube, do you have OBS? You should try streaming your screen to Youtube using OBS to see if that works. Other than that I don't have too many ideas on what's wrong.

**Comment by kubi-ozisik** [comment]
there is no problem with OBS. But I need to integrate this functionality into my app. It's a web app. There must be something different with the encoding parameters. It seems Japanese to me right now but I'll learn how to tweak it.
